# NumPy Questions


### Q1. Import numpy as np

In [1]:
import numpy as np

### Q2. Print numpy version and configuration

In [2]:
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

### Q3. Create a null vector of size 10

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Q4. Find memory size of an array

In [4]:
print(Z.nbytes)

80


### Q6. Null vector size 10, 5th value = 1

In [5]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Q7. Vector from 10 to 49

In [6]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Q8. Reverse a vector

In [7]:
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### Q9. 3x3 matrix with values 0 to 8

In [8]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Q10. Indices of non-zero elements

In [9]:
Z = np.array([1,2,0,0,4,0])
print(np.nonzero(Z))

(array([0, 1, 4]),)


### Q11. Identity matrix

In [10]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Q12. 3x3x3 random array

In [11]:
print(np.random.random((3,3,3)))

[[[0.35669973 0.52685676 0.00239247]
  [0.60140076 0.54376567 0.20107273]
  [0.79408655 0.4157144  0.01104734]]

 [[0.10542862 0.81473336 0.59455167]
  [0.90187738 0.93853246 0.50605441]
  [0.74745175 0.67135987 0.49325996]]

 [[0.1795787  0.4175133  0.6406024 ]
  [0.19440274 0.60276979 0.50188649]
  [0.65180549 0.58998593 0.68700459]]]


### Q13. Min and max of random 10x10 array

In [12]:
Z = np.random.random((10,10))
print(Z.min(), Z.max())

0.019034283386814788 0.9777110596907622


### Q14. Mean of random vector size 30

In [13]:
Z = np.random.random(30)
print(Z.mean())

0.4536836873976728


### Q15. 2D array with border 1 and inside 0

In [14]:
Z = np.ones((5,5))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Q16. Add border of zeros

In [15]:
Z = np.ones((3,3))
print(np.pad(Z,1))

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### Q17. Expressions with NaN

In [16]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(np.nan in set([np.nan]))
print(0.3==3*0.1)

nan
False
False
nan
True
False


### Q30. Common values between two arrays

In [17]:
A = np.array([1,2,3,4])
B = np.array([3,4,5,6])
print(np.intersect1d(A,B))

[3 4]


### Q37. 5x5 matrix with rows 0 to 4

In [18]:
Z = np.tile(np.arange(5),(5,1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### Q44. Cartesian to polar coordinates

In [19]:
Z = np.random.random((10,2))
x = Z[:,0]
y = Z[:,1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y,x)
print(r,theta)

[0.91495396 0.3369888  0.68315905 0.78116012 0.34543387 0.31435886
 0.14890095 0.72723182 1.09817285 1.01028129] [0.37007154 0.22124259 1.384911   1.48331985 0.01910094 1.48939346
 1.19973929 0.89288629 0.45902506 0.38295295]


### Q50. Closest value to scalar

In [20]:
Z = np.array([1,3,7,10])
x = 6
print(Z[np.abs(Z-x).argmin()])

7


### Q70. Insert 3 zeros between values

In [21]:
Z = np.array([1,2,3,4,5])
R = np.zeros(len(Z)*4-3)
R[::4] = Z
print(R)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


### Q83. Most frequent value

In [23]:
Z = np.array([1,2,2,3,3,3,4])
values, counts = np.unique(Z, return_counts=True)
print(values[counts.argmax()])

3
